apiVersion: v1
kind: Pod
metadata:
  name: vault
  namespace: default
  labels:
    name: vault
spec:
  containers:
  - name: vault-container
    image: vault:1.13.3
    ports:
      - containerPort: 8200
        name: http