apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: spb-ippool
spec:
  cidr: 192.168.0.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: name == "spb"
---
apiVersion: projectcalico.org/v3
kind: IPPool
metadata:
  name: msk-ippool
spec:
  cidr: 192.168.1.0/24
  ipipMode: Always
  natOutgoing: true
  nodeSelector: name == "msk"